# Generated by inst/scripts/generate_theme_functions.R: do not edit by hand

#' @param text_color Text Color. Defaults to #000. Modifies the `body` element.
#'   The value of this variable is also stored as a CSS variable that can be
#'   referenced with `var(--text_color)` in any argument of a style function or
#'   in custom CSS.
#' @param header_color Header Color. Defaults to #000. Modifies the
#'   `h1, h2, h3` elements. The value of this variable is also stored as a CSS
#'   variable that can be referenced with `var(--header-color)` in any argument
#'   of a style function or in custom CSS.
#' @param background_color Slide Background Color. Defaults to #FFF. Modifies
#'   the `.remark-slide-content` class. The value of this variable is also
#'   stored as a CSS variable that can be referenced with
#'   `var(--background-color)` in any argument of a style function or in custom
#'   CSS.
#' @param link_color Link Color. Defaults to rgb(249, 38, 114). Modifies the
#'   `a, a > code` elements. The value of this variable is also stored as a CSS
#'   variable that can be referenced with `var(--link-color)` in any argument
#'   of a style function or in custom CSS.
#' @param text_bold_color Bold Text Color. Defaults to `NULL`. Modifies the
#'   `strong` element. The value of this variable is also stored as a CSS
#'   variable that can be referenced with `var(--text-bold-color)` in any
#'   argument of a style function or in custom CSS.
#' @param text_slide_number_color Slide Number Color. Defaults to
#'   `inverse_background_color`. Modifies the `.remark-slide-number` class. The
#'   value of this variable is also stored as a CSS variable that can be
#'   referenced with `var(NA)` in any argument of a style function or in custom
#'   CSS.
#' @param padding Slide Padding in `top right [bottom left]` format. Defaults
#'   to 16px 64px 16px 64px. Modifies the `.remark-slide-content` class. The
#'   value of this variable is also stored as a CSS variable that can be
#'   referenced with `var(NA)` in any argument of a style function or in custom
#'   CSS.
#' @param background_image Background image applied to each *and every* slide.
#'   Set `title_slide_background_image = "none"` to remove the background image
#'   from the title slide. Defaults to `NULL`. Modifies the
#'   `.remark-slide-content` class. The value of this variable is also stored
#'   as a CSS variable that can be referenced with `var(NA)` in any argument of
#'   a style function or in custom CSS.
#' @param background_size Background image size, requires `background_image` to
#'   be set. If `background_image` is set, `background_size` will default to
#'   `cover` so the backround fills the screen. If both `background_image` and
#'   `background_position` are set, will default to 100 percent. Defaults to
#'   `NULL`. Modifies the `.remark-slide-content` class. The value of this
#'   variable is also stored as a CSS variable that can be referenced with
#'   `var(NA)` in any argument of a style function or in custom CSS.
#' @param background_position Background image position, requires
#'   `background_image` to be set, and it is recommended to adjust
#'   `background_size`. Defaults to `NULL`. Modifies the
#'   `.remark-slide-content` class. The value of this variable is also stored
#'   as a CSS variable that can be referenced with `var(NA)` in any argument of
#'   a style function or in custom CSS.
#' @param code_highlight_color Code Line Highlight. Defaults to
#'   rgba(255,255,0,0.5). Modifies the `.remark-code-line-highlighted` class.
#'   The value of this variable is also stored as a CSS variable that can be
#'   referenced with `var(--code-highlight-color)` in any argument of a style
#'   function or in custom CSS.
#' @param code_inline_color Inline Code Color. Defaults to #000. Modifies the
#'   `.remark-inline-code` class. The value of this variable is also stored as
#'   a CSS variable that can be referenced with `var(NA)` in any argument of a
#'   style function or in custom CSS.
#' @param code_inline_background_color Inline Code Background Color. Defaults
#'   to `NULL`. Modifies the `.remark-inline-code` class. The value of this
#'   variable is also stored as a CSS variable that can be referenced with
#'   `var(NA)` in any argument of a style function or in custom CSS.
#' @param code_inline_font_size Inline Code Text Font Size. Defaults to 1em.
#'   Modifies the `.remark-inline-code` class. The value of this variable is
#'   also stored as a CSS variable that can be referenced with
#'   `var(--code-inline-font-size)` in any argument of a style function or in
#'   custom CSS.
#' @param inverse_background_color Inverse Background Color. Defaults to
#'   #272822. Modifies the `.inverse` class. The value of this variable is also
#'   stored as a CSS variable that can be referenced with
#'   `var(--inverse-background-color)` in any argument of a style function or
#'   in custom CSS.
#' @param inverse_text_color Inverse Text Color. Defaults to #d6d6d6. Modifies
#'   the `.inverse` class. The value of this variable is also stored as a CSS
#'   variable that can be referenced with `var(--inverse-text-color)` in any
#'   argument of a style function or in custom CSS.
#' @param inverse_text_shadow Enables Shadow on text of inverse slides.
#'   Defaults to `FALSE`. Modifies the `.inverse` class. The value of this
#'   variable is also stored as a CSS variable that can be referenced with
#'   `var(NA)` in any argument of a style function or in custom CSS.
#' @param inverse_header_color Inverse Header Color. Defaults to #f3f3f3.
#'   Modifies the `.inverse h1, .inverse h2, .inverse h3` classes. The value of
#'   this variable is also stored as a CSS variable that can be referenced with
#'   `var(--inverse-header-color)` in any argument of a style function or in
#'   custom CSS.
#' @param title_slide_text_color Title Slide Text Color. Defaults to
#'   `inverse_text_color`. Modifies the `.title-slide` class. The value of this
#'   variable is also stored as a CSS variable that can be referenced with
#'   `var(--title-slide-text-color)` in any argument of a style function or in
#'   custom CSS.
#' @param title_slide_background_color Title Slide Background Color. Defaults
#'   to `inverse_background_color`. Modifies the `.title-slide` class. The
#'   value of this variable is also stored as a CSS variable that can be
#'   referenced with `var(--title-slide-background-color)` in any argument of a
#'   style function or in custom CSS.
#' @param title_slide_background_image Title Slide Background Image URL.
#'   Defaults to `NULL`. Modifies the `.title-slide` class. The value of this
#'   variable is also stored as a CSS variable that can be referenced with
#'   `var(NA)` in any argument of a style function or in custom CSS.
#' @param title_slide_background_size Title Slide Background Image Size,
#'   defaults to "cover" if background image is set. Defaults to `NULL`.
#'   Modifies the `.title-slide` class. The value of this variable is also
#'   stored as a CSS variable that can be referenced with `var(NA)` in any
#'   argument of a style function or in custom CSS.
#' @param title_slide_background_position Title Slide Background Image
#'   Position. Defaults to `NULL`. Modifies the `.title-slide` class. The value
#'   of this variable is also stored as a CSS variable that can be referenced
#'   with `var(NA)` in any argument of a style function or in custom CSS.
#' @param footnote_color Footnote text color (if `NA`, then it will be the same
#'   color as `text_color`). Defaults to `NULL`. Modifies the `.footnote`
#'   class. The value of this variable is also stored as a CSS variable that
#'   can be referenced with `var(NA)` in any argument of a style function or in
#'   custom CSS.
#' @param footnote_font_size Footnote font size. Defaults to 0.9em. Modifies
#'   the `.footnote` class. The value of this variable is also stored as a CSS
#'   variable that can be referenced with `var(NA)` in any argument of a style
#'   function or in custom CSS.
#' @param footnote_position_bottom Footnote location from bottom of screen.
#'   Defaults to 60px. Modifies the `.footnote` class. The value of this
#'   variable is also stored as a CSS variable that can be referenced with
#'   `var(NA)` in any argument of a style function or in custom CSS.
#' @param left_column_subtle_color Left Column Text (not last). Defaults to
#'   #777. Modifies the `.left-column h2, .left-column h3` classes. The value
#'   of this variable is also stored as a CSS variable that can be referenced
#'   with `var(NA)` in any argument of a style function or in custom CSS.
#' @param left_column_selected_color Left Column Current Selection. Defaults to
#'   #000. Modifies the
#'   `.left-column h2:last-of-type, .left-column h3:last-child` classes. The
#'   value of this variable is also stored as a CSS variable that can be
#'   referenced with `var(NA)` in any argument of a style function or in custom
#'   CSS.
#' @param blockquote_left_border_color Blockquote Left Border Color. Defaults
#'   to lightgray. Modifies the `blockquote` element. The value of this
#'   variable is also stored as a CSS variable that can be referenced with
#'   `var(NA)` in any argument of a style function or in custom CSS.
#' @param table_border_color Table top/bottom border. Defaults to #666.
#'   Modifies the `table: border-top, border-bottom` elements. The value of
#'   this variable is also stored as a CSS variable that can be referenced with
#'   `var(NA)` in any argument of a style function or in custom CSS.
#' @param table_row_border_color Table row inner bottom border. Defaults to
#'   #ddd. Modifies the `table thead th: border-bottom` elements. The value of
#'   this variable is also stored as a CSS variable that can be referenced with
#'   `var(NA)` in any argument of a style function or in custom CSS.
#' @param table_row_even_background_color Table Even Row Background Color.
#'   Defaults to #eee. Modifies the `thead, tfoot, tr:nth-child(even)`
#'   elements. The value of this variable is also stored as a CSS variable that
#'   can be referenced with `var(NA)` in any argument of a style function or in
#'   custom CSS.
#' @param base_font_size Base Font Size for All Slide Elements (must be `px`).
#'   Defaults to 20px. Modifies the `html` element. The value of this variable
#'   is also stored as a CSS variable that can be referenced with
#'   `var(--base-font-size)` in any argument of a style function or in custom
#'   CSS.
#' @param text_font_size Slide Body Text Font Size. Defaults to 1rem. Modifies
#'   the `.remark-slide-content` class. The value of this variable is also
#'   stored as a CSS variable that can be referenced with
#'   `var(--text-font-size)` in any argument of a style function or in custom
#'   CSS.
#' @param header_h1_font_size h1 Header Text Font Size. Defaults to 2.75rem.
#'   Modifies the `.remark-slide-content h1` class. The value of this variable
#'   is also stored as a CSS variable that can be referenced with
#'   `var(--header-h1-font-size)` in any argument of a style function or in
#'   custom CSS.
#' @param header_h2_font_size h2 Header Text Font Size. Defaults to 2.25rem.
#'   Modifies the `.remark-slide-content h2` class. The value of this variable
#'   is also stored as a CSS variable that can be referenced with
#'   `var(--header-h2-font-size)` in any argument of a style function or in
#'   custom CSS.
#' @param header_h3_font_size h3 Header Text Font Size. Defaults to 1.75rem.
#'   Modifies the `.remark-slide-content h3` class. The value of this variable
#'   is also stored as a CSS variable that can be referenced with
#'   `var(--header-h3-font-size)` in any argument of a style function or in
#'   custom CSS.
#' @param header_background_auto Add background under slide title automatically
#'   for h1 header elements. If not enabled, use `class: header_background` to
#'   enable. Defaults to `FALSE`.  The value of this variable is also stored as
#'   a CSS variable that can be referenced with `var(NA)` in any argument of a
#'   style function or in custom CSS.
#' @param header_background_color Background Color for h1 Header with
#'   Background. Defaults to `header_color`. Modifies the
#'   `.remark-slide-content h1` class. The value of this variable is also
#'   stored as a CSS variable that can be referenced with
#'   `var(--header-background-color)` in any argument of a style function or in
#'   custom CSS.
#' @param header_background_text_color Text Color for h1 Header with
#'   Background. Defaults to `background_color`. Modifies the
#'   `.remark-slide-content h1` class. The value of this variable is also
#'   stored as a CSS variable that can be referenced with
#'   `var(--header-background-text-color)` in any argument of a style function
#'   or in custom CSS.
#' @param header_background_padding Padding for h1 Header with Background.
#'   Defaults to `NULL`. Modifies the `.remark-slide-content h1` class. The
#'   value of this variable is also stored as a CSS variable that can be
#'   referenced with `var(NA)` in any argument of a style function or in custom
#'   CSS.
#' @param header_background_content_padding_top Top Padding for Content in
#'   Slide with Header with Background. Defaults to 7rem. Modifies the
#'   `.remark-slide-content` class. The value of this variable is also stored
#'   as a CSS variable that can be referenced with `var(NA)` in any argument of
#'   a style function or in custom CSS.
#' @param header_background_ignore_classes Slide Classes Where Header with
#'   Background will not be Applied. Defaults to
#'   `c('normal', 'inverse', 'title', 'middle', 'bottom')`. Modifies the
#'   `.remark-slide-content` class. The value of this variable is also stored
#'   as a CSS variable that can be referenced with `var(NA)` in any argument of
#'   a style function or in custom CSS.
#' @param text_slide_number_font_size Slide Number Text Font Size. Defaults to
#'   0.9em. Modifies the `.remark-slide-number` class. The value of this
#'   variable is also stored as a CSS variable that can be referenced with
#'   `var(NA)` in any argument of a style function or in custom CSS.
#' @param text_font_google Use `google_font()` to specify body font. Defaults
#'   to `NULL`. Modifies the `body` element. The value of this variable is also
#'   stored as a CSS variable that can be referenced with `var(NA)` in any
#'   argument of a style function or in custom CSS.
#' @param text_font_family Body Text Font Family (xaringan default is
#'   `'Droid Serif'`). Defaults to Noto Sans. Modifies the `body` element. The
#'   value of this variable is also stored as a CSS variable that can be
#'   referenced with `var(--text-font-family)` in any argument of a style
#'   function or in custom CSS.
#' @param text_font_weight Body Text Font Weight. Defaults to normal. Modifies
#'   the `body` element. The value of this variable is also stored as a CSS
#'   variable that can be referenced with `var(NA)` in any argument of a style
#'   function or in custom CSS.
#' @param text_font_url Body Text Font URL(s). Defaults to
#'   https://fonts.googleapis.com/css?family=Noto+Sans:400,400i,700,700i&display=swap.
#'   Modifies the `@import url()` elements. The value of this variable is also
#'   stored as a CSS variable that can be referenced with `var(NA)` in any
#'   argument of a style function or in custom CSS.
#' @param text_font_family_fallback Body Text Font Fallbacks. Defaults to
#'   -apple-system, BlinkMacSystemFont, avenir next, avenir, helvetica neue,
#'   helvetica, Ubuntu, roboto, noto, segoe ui, arial. Modifies the `body`
#'   element. The value of this variable is also stored as a CSS variable that
#'   can be referenced with `var(--text-font-family-fallback)` in any argument
#'   of a style function or in custom CSS.
#' @param text_font_base Body Text Base Font (Total Failure Fallback). Defaults
#'   to sans-serif. Modifies the `body` element. The value of this variable is
#'   also stored as a CSS variable that can be referenced with
#'   `var(--text-font-base)` in any argument of a style function or in custom
#'   CSS.
#' @param header_font_google Use `google_font()` to specify header font.
#'   Defaults to `NULL`. Modifies the `body` element. The value of this
#'   variable is also stored as a CSS variable that can be referenced with
#'   `var(NA)` in any argument of a style function or in custom CSS.
#' @param header_font_family Header Font Family (xaringan default is
#'   `'Yanone Kaffeesatz'`). Defaults to Cabin. Modifies the `h1, h2, h3`
#'   elements. The value of this variable is also stored as a CSS variable that
#'   can be referenced with `var(--header-font-family)` in any argument of a
#'   style function or in custom CSS.
#' @param header_font_weight Header Font Weight. Defaults to 600. Modifies the
#'   `h1, h2, h3` elements. The value of this variable is also stored as a CSS
#'   variable that can be referenced with `var(NA)` in any argument of a style
#'   function or in custom CSS.
#' @param header_font_url Header Font URL. Defaults to
#'   https://fonts.googleapis.com/css?family=Cabin:600,600i&display=swap.
#'   Modifies the `@import url` elements. The value of this variable is also
#'   stored as a CSS variable that can be referenced with `var(NA)` in any
#'   argument of a style function or in custom CSS.
#' @param code_font_google Use `google_font()` to specify code font. Defaults
#'   to `NULL`. Modifies the `body` element. The value of this variable is also
#'   stored as a CSS variable that can be referenced with `var(NA)` in any
#'   argument of a style function or in custom CSS.
#' @param code_font_family Code Font Family. Defaults to Source Code Pro.
#'   Modifies the `.remark-code, .remark-inline-code` classes. The value of
#'   this variable is also stored as a CSS variable that can be referenced with
#'   `var(--code-font-family)` in any argument of a style function or in custom
#'   CSS.
#' @param code_font_size Code Text Font Size. Defaults to 0.9rem. Modifies the
#'   `.remark-inline` class. The value of this variable is also stored as a CSS
#'   variable that can be referenced with `var(--code-font-size)` in any
#'   argument of a style function or in custom CSS.
#' @param code_font_url Code Font URL. Defaults to
#'   https://fonts.googleapis.com/css?family=Source+Code+Pro:400,700&display=swap.
#'   Modifies the `@import url` elements. The value of this variable is also
#'   stored as a CSS variable that can be referenced with `var(NA)` in any
#'   argument of a style function or in custom CSS.
#' @param code_font_family_fallback Code Font Fallback. Defaults to Menlo,
#'   Consolas, Monaco, Liberation Mono, Lucida Console. Modifies the
#'   `.remark-code, .remark-inline-code` classes. The value of this variable is
#'   also stored as a CSS variable that can be referenced with `var(NA)` in any
#'   argument of a style function or in custom CSS.
#' @template theme_params
#' @template style_xaringan
#' @export
style_xaringan <- function(
  text_color = "#000",
  header_color = "#000",
  background_color = "#FFF",
  link_color = "rgb(249, 38, 114)",
  text_bold_color = NULL,
  text_slide_number_color = inverse_background_color,
  padding = "16px 64px 16px 64px",
  background_image = NULL,
  background_size = NULL,
  background_position = NULL,
  code_highlight_color = "rgba(255,255,0,0.5)",
  code_inline_color = "#000",
  code_inline_background_color = NULL,
  code_inline_font_size = "1em",
  inverse_background_color = "#272822",
  inverse_text_color = "#d6d6d6",
  inverse_text_shadow = FALSE,
  inverse_header_color = "#f3f3f3",
  title_slide_text_color = inverse_text_color,
  title_slide_background_color = inverse_background_color,
  title_slide_background_image = NULL,
  title_slide_background_size = NULL,
  title_slide_background_position = NULL,
  footnote_color = NULL,
  footnote_font_size = "0.9em",
  footnote_position_bottom = "60px",
  left_column_subtle_color = "#777",
  left_column_selected_color = "#000",
  blockquote_left_border_color = "lightgray",
  table_border_color = "#666",
  table_row_border_color = "#ddd",
  table_row_even_background_color = "#eee",
  base_font_size = "20px",
  text_font_size = "1rem",
  header_h1_font_size = "2.75rem",
  header_h2_font_size = "2.25rem",
  header_h3_font_size = "1.75rem",
  header_background_auto = FALSE,
  header_background_color = header_color,
  header_background_text_color = background_color,
  header_background_padding = NULL,
  header_background_content_padding_top = "7rem",
  header_background_ignore_classes = c('normal', 'inverse', 'title', 'middle', 'bottom'),
  text_slide_number_font_size = "0.9em",
  text_font_google = NULL,
  text_font_family = "Noto Sans",
  text_font_weight = "normal",
  text_font_url = "https://fonts.googleapis.com/css?family=Noto+Sans:400,400i,700,700i&display=swap",
  text_font_family_fallback = "-apple-system, BlinkMacSystemFont, avenir next, avenir, helvetica neue, helvetica, Ubuntu, roboto, noto, segoe ui, arial",
  text_font_base = "sans-serif",
  header_font_google = NULL,
  header_font_family = "Cabin",
  header_font_weight = "600",
  header_font_url = "https://fonts.googleapis.com/css?family=Cabin:600,600i&display=swap",
  code_font_google = NULL,
  code_font_family = "Source Code Pro",
  code_font_size = "0.9rem",
  code_font_url = "https://fonts.googleapis.com/css?family=Source+Code+Pro:400,700&display=swap",
  code_font_family_fallback = "Menlo, Consolas, Monaco, Liberation Mono, Lucida Console",
  colors = NULL,
  extra_css = NULL,
  extra_fonts = NULL,
  outfile = "xaringan-themer.css"
) {
  # DO NOT EDIT - Generated from inst/scripts/generate_theme_functions.R
  # Make sure font names are wrapped in quotes if they have spaces
  f_args <- names(formals(sys.function()))
  for (var in f_args[grepl("font_family$", f_args)]) {
    var_value <- get(var, inherits = FALSE)
    if (!is.null(var_value)) {
      eval(parse(text = paste0(var, "<-quote_elements_w_spaces(", var, ")")))
    }
    # set an is_google flag default of FALSE that is possibly overwritten later
    eval(parse(text = paste0(sub("font_family$", "font_is_google", var), "<-0")))
  }
  
  # Warn if base_font_size isn't absolute
  css_abs_units <- c("cm", "mm", "Q", "in", "pc", "pt", "px")
  if (!grepl(paste(tolower(css_abs_units), collapse = "|"), tolower(base_font_size))) {
    warning(
      glue::glue(
        "Base font size '{base_font_size}' is not in absolute units. ",
        "For best results, specify the `base_font_size` using absolute CSS units: ",
        "{paste(css_abs_units, collapse = ', ')}"
      ),
      call. = FALSE,
      immediate. = TRUE
    )
  }
  
  # Use font_..._google args to overwrite font args
  for (var in f_args[grepl("font_google$", f_args)]) {
    gf <- eval(parse(text = var))
    if (is.null(gf)) next
    if (!inherits(gf, "google_font")) {
      stop("`", var, "` must be set using `google_font()`.")
    }
    group <- strsplit(var, "_")[[1]][1]
    if (group == "text") {
      text_font_family <- quote_elements_w_spaces(gf$family)
      text_font_weight <- gf$weights %||% "normal"
      text_font_weight <- substr(text_font_weight, 1, regexpr(",", text_font_weight)[1] - 1)
      text_font_url <- gf$url
    } else {
      eval(parse(text = paste0(group, "_font_family <- quote_elements_w_spaces(gf$family)")))
      eval(parse(text = paste0(group, "_font_url <- gf$url")))
    }
    eval(parse(text = paste0(group, "_font_is_google <- 1")))
  }
  
  is_default <- function(type, suffix, reference = style_xaringan) {
    var <- paste0(type, "_", suffix)
    default_value <- formals(reference)[[var]]
    if (suffix == "font_family") {
      default_value <- quote_elements_w_spaces(default_value)
    }
  
    get(var, envir = parent.frame(2), inherits = FALSE) == default_value
  }
  
  # the defaults are google fonts
  for (var in c("text", "header", "code")) {
    suffixes <- c("font_family", "font_weight", "font_url")
    if (var == "code") suffixes <- setdiff(suffixes, "font_weight")
    var_is_google <- all(vapply(suffixes, is_default, logical(1), type = var))
    if (var_is_google) {
      eval(parse(text = paste0(var, "_font_is_google <- 1")))
    }
  }
  
  extra_font_imports <- if (is.null(extra_fonts)) "" else list2fonts(extra_fonts)
  extra_font_imports <- paste(extra_font_imports, collapse = "\n")
  
  # convert NA arguments to NULL
  for (var in f_args) {
    val <- eval(parse(text = var))
    if (is.null(val)) next
    val <- val[!is.na(val)]
    is_na <- length(val) == 0
    if (is_na) assign(var, NULL)
  }
  
  # prepare variables for template
  body_font_family <- paste(c(text_font_family, text_font_family_fallback, text_font_base), collapse = ", ")
  background_size_fallback <- if (is.null(background_position)) "cover" else "100%"
  background_size <- background_image %??% (background_size %||% background_size_fallback)
  title_slide_background_size <- title_slide_background_size %||% (
    title_slide_background_image %??% "cover"
  )
  table_row_even_background_color <- table_row_even_background_color %||% background_color
  
  # stash theme settings in package env
  lapply(f_args, function(n) assign(n, get(n), envir = xaringanthemer_env))
  for (font_is_google in paste0(c("text", "code", "header"), "_font_is_google")) {
    assign(
      font_is_google,
      get(font_is_google, inherits = FALSE) == 1,
      envir = xaringanthemer_env
    )
  }
  
  xaringanthemer_version <- utils::packageVersion("xaringanthemer")
  
  # prepare header background object
  needs_leading_dot <- !grepl("^\\.", header_background_ignore_classes)
  header_background_ignore_classes[needs_leading_dot] <- paste0(
    ".",
    header_background_ignore_classes[needs_leading_dot]
  )
  header_background_ignore_classes <- purrr::map(
    header_background_ignore_classes,
    ~ list(class = .)
  )
  if (is.null(header_background_padding)) {
    slide_padding <- css_get_padding(padding)
    header_background_padding <- paste(
      "2rem", slide_padding$right, "1.5rem", slide_padding$left
    )
  }
  header_background <- list(
    auto = header_background_auto,
    background_color = header_background_color,
    text_color = header_background_text_color,
    padding = header_background_padding,
    content_padding_top = header_background_content_padding_top,
    ignore = header_background_ignore_classes
  )
  
  colors <- prepare_colors(colors)
  
  tf <- system.file("resources", "template.css", package = "xaringanthemer")
  template <- readLines(tf, warn = FALSE)
  template <- paste(template, collapse = "\n")
  x <- whisker::whisker.render(template)
  if (!is.null(extra_css)) {
    x <- c(x, style_extra_css(extra_css, outfile = NULL))
  }
  if (is.null(outfile)) {
    return(x)
  }
  writeLines(x, con = outfile)
  invisible(outfile)
}
